In [1]:
import os 
import csv
import pandas as pd 
import numpy as np

In [2]:
bachelor = pd.read_csv("bachelor-contestants.csv", encoding = "ISO-8859-1")
bachelor.head()

Name  Age                       Occupation  Job Category  \
0   Amanda   23                    Event Planner             6   
1   Trista   29                Miami Heat Dancer             5   
2  Shannon   24  Financial Management Consultant             8   
3      Kim   24                            Nanny             1   
4    Cathy   22                 Graduate Student             3   

  Job Category Description     Hometown    State  Height(in)  Weight(lbs)  \
0                  Service      Chanute   Kansas        65.0           91   
1                Corporate        Miami  Florida        66.0          104   
2            Entertainment       Dallas    Texas        64.0          156   
3                 Medicine        Tempe  Arizona        61.0          116   
4                   Retail  Terra Haute  Indiana        66.0          112   

   Hair Color Code Hair Color  Eye Color Code Eye Color  ElimWeek  Season  
0                2     Blonde               1      Blue         1       1  
1                1      Black               2     Brown         6       1  
2                2     Blonde               4     Black         5       1  
3                3   Brunette               1      Blue         4       1  
4                2     Blonde               3     Green         3       1

In [3]:
bachelor_df = bachelor.drop(columns=['Name', 'Hometown', 'Occupation', 'Job Category Description', 'Hair Color', 'Eye Color'])
bachelor_df.head()

Age  Job Category    State  Height(in)  Weight(lbs)  Hair Color Code  \
0   23             6   Kansas        65.0           91                2   
1   29             5  Florida        66.0          104                1   
2   24             8    Texas        64.0          156                2   
3   24             1  Arizona        61.0          116                3   
4   22             3  Indiana        66.0          112                2   

   Eye Color Code  ElimWeek  Season  
0               1         1       1  
1               2         6       1  
2               4         5       1  
3               1         4       1  
4               3         3       1

In [4]:
X = bachelor_df.drop("ElimWeek", axis=1)
y = bachelor_df["ElimWeek"]
print(X.shape, y.shape)

(423, 8) (423,)


In [5]:
# import SKlearn model and preprocessing kits 

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from keras.utils import to_categorical

C:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [6]:
#Label-encode job category
label_encoder = LabelEncoder()
label_encoder.fit(X["Job Category"])
X2 = X
encoded_X_jc = label_encoder.transform(X["Job Category"])
X2["Job Category"] = encoded_X_jc

#Label-encode hair color 
label_encoder = LabelEncoder()
label_encoder.fit(X["Hair Color Code"])
X2 = X
encoded_X_hair = label_encoder.transform(X["Hair Color Code"])
X2["Hair Color Code"] = encoded_X_hair

#label-encode eye color 
label_encoder = LabelEncoder()
label_encoder.fit(X["Eye Color Code"])
X2 = X
encoded_X_eye = label_encoder.transform(X["Eye Color Code"])
X2["Eye Color Code"] = encoded_X_eye

# label-encode season
label_encoder = LabelEncoder()
label_encoder.fit(X["Season"])
X2 = X
encoded_X_season = label_encoder.transform(X["Season"])
X2["Season"] = encoded_X_season

# label-encode states
label_encoder = LabelEncoder()
label_encoder.fit(X["State"])
X2 = X
encoded_X_state = label_encoder.transform(X["State"])
X2["State"] = encoded_X_state

# label-encode y 
one_hot_y = to_categorical(y)

In [ ]:
for label, original_class in zip(encoded_X_jc, X["Job Category"]):
    print('Original Class: ' + str(original_class))
    print('Encoded Label: ' + str(label))
    print('-' * 12)

In [ ]:
for label, original_class in zip(encoded_X_hair, X["Hair Color Code"]):
    print('Original Class: ' + str(original_class))
    print('Encoded Label: ' + str(label))
    print('-' * 12)

In [ ]:
for label, original_class in zip(encoded_X_eye, X["Eye Color Code"]):
    print('Original Class: ' + str(original_class))
    print('Encoded Label: ' + str(label))
    print('-' * 12)

In [ ]:
for label, original_class in zip(encoded_X_season, X["Season"]):
    print('Original Class: ' + str(original_class))
    print('Encoded Label: ' + str(label))
    print('-' * 12)

In [ ]:
for label, original_class in zip(encoded_X_state, X["State"]):
    print('Original Class: ' + str(original_class))
    print('Encoded Label: ' + str(label))
    print('-' * 12)

In [12]:
#One-hot encoding
one_hot_jc= to_categorical(encoded_X_jc)
one_hot_jc

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])

In [13]:
one_hot_hair = to_categorical(encoded_X_hair)
one_hot_hair

array([[0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       ...,
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.]])

In [14]:
one_hot_eye = to_categorical(encoded_X_eye)
one_hot_eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       ...,
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.]])

In [15]:
one_hot_season = to_categorical(encoded_X_season)
one_hot_season

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [16]:
one_hot_state = to_categorical(encoded_X_state)
one_hot_state

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [17]:
########################################################

In [266]:
X_train, X_test, y_train, y_test = train_test_split(X2, one_hot_y, random_state=1, stratify=y,shuffle=True)


X_scaler = StandardScaler().fit(X_train)

X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

y_scaler =y_scaler = StandardScaler().fit(y_train)

y_train_scaled = y_scaler.transform(y_train)
y_test_scaled = y_scaler.transform(y_test)

# The output layer has 11 columns that are one-hot encoded
y_train.shape

(317, 11)

In [267]:
X_train.shape

(317, 8)

In [285]:
from keras.models import Sequential
from keras.utils import to_categorical
from keras.layers import Dense,Dropout, Flatten
from keras import regularizers

number_inputs = 8

model = Sequential()

model.add(Dense(88, activation='relu', input_dim=number_inputs,kernel_regularizer=regularizers.l2(0.05),
                activity_regularizer=regularizers.l2(0.03)))
    #https://faroit.github.io/keras-docs/1.1.1/regularizers/#example
    
model.add(Dropout(0.2))

model.add(Dense(44, activation='tanh'))
model.add(Dropout(0.5))

model.add(Dense(22, activation='tanh'))
model.add(Dropout(0.5))

model.add(Dense(15, activation='tanh'))

# Output layer
model.add(Dense(11, activation='softmax'))
model.add(Dropout(0.2))

# Model compile
model.compile(loss="categorical_crossentropy", optimizer="adam", metrics=['accuracy'])
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_301 (Dense)            (None, 88)                792       
_________________________________________________________________
dropout_160 (Dropout)        (None, 88)                0         
_________________________________________________________________
dense_302 (Dense)            (None, 44)                3916      
_________________________________________________________________
dropout_161 (Dropout)        (None, 44)                0         
_________________________________________________________________
dense_303 (Dense)            (None, 22)                990       
_________________________________________________________________
dropout_162 (Dropout)        (None, 22)                0         
_________________________________________________________________
dense_304 (Dense)            (None, 15)                345       
__________

In [286]:
# Use the training data to fit (train) the model
model.fit(
    X_train_scaled,
    y_train_scaled,
    epochs=40, #35-40 before loss skyrockets with current parameters
    shuffle=False, 
    verbose=True,
    batch_size = 11
)

Epoch 1/40
317/317 [==============================] - 2s 7ms/step - loss: 2.3849 - acc: 0.0789
Epoch 2/40
317/317 [==============================] - 0s 531us/step - loss: 2.9905 - acc: 0.1073
Epoch 3/40
317/317 [==============================] - 0s 528us/step - loss: 0.0327 - acc: 0.1104
Epoch 4/40
317/317 [==============================] - 0s 491us/step - loss: -0.7409 - acc: 0.0820
Epoch 5/40
317/317 [==============================] - 0s 512us/step - loss: 1.0447 - acc: 0.1483
Epoch 6/40
317/317 [==============================] - 0s 554us/step - loss: 1.5336 - acc: 0.1325
Epoch 7/40
317/317 [==============================] - 0s 595us/step - loss: 1.0372 - acc: 0.0883
Epoch 8/40
317/317 [==============================] - 0s 535us/step - loss: -0.7477 - acc: 0.1546
Epoch 9/40
317/317 [==============================] - 0s 554us/step - loss: -1.0710 - acc: 0.1640
Epoch 10/40
317/317 [==============================] - 0s 519us/step - loss: 0.2303 - acc: 0.1735
Epoch 11/40
317/317 [=======

In [287]:
# Evaluate the model using the training data 
model_loss, model_accuracy = model.evaluate(X_test_scaled, y_test_scaled, verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Loss: -2.8599845688298062, Accuracy: 0.2924528304698332


In [288]:
model.predict_classes(X_test_scaled)

array([ 1,  3,  1,  1,  1,  1,  1,  1,  1,  1,  8, 10,  1,  1,  1,  1,  1,
        1,  7,  1,  1, 10,  1, 10,  1,  1,  1,  7,  1,  1,  9,  1,  1, 10,
        1,  1, 10,  7,  1,  8, 10,  1,  7,  1,  1,  1,  1, 10,  7,  1,  1,
        1, 10,  9, 10, 10, 10,  1,  1,  1,  1,  1, 10,  1,  1, 10, 10, 10,
       10,  1,  7, 10,  1,  1,  1, 10, 10, 10,  1, 10,  1,  1,  1,  1,  1,
        1,  1, 10,  8,  1,  1,  1,  9,  1,  1, 10,  1,  1,  1,  1, 10,  1,
        1,  1,  1,  3], dtype=int64)

In [289]:
model.predict(X_test_scaled)

array([[1.8842586e-03, 9.7337669e-01, 2.3111576e-02, ..., 6.1820063e-04,
        2.9733069e-08, 2.6969039e-08],
       [4.1845839e-02, 4.3501982e-01, 4.6264149e-02, ..., 7.6681278e-03,
        1.6606952e-03, 2.8437872e-03],
       [4.0534306e-03, 9.7527814e-01, 1.7201774e-02, ..., 1.5464848e-03,
        2.8736795e-07, 4.0479023e-07],
       ...,
       [1.8255546e-03, 9.7348481e-01, 2.3026576e-02, ..., 5.5746798e-04,
        2.8716453e-08, 2.4223596e-08],
       [1.8323788e-03, 9.7337657e-01, 2.3131309e-02, ..., 5.6719832e-04,
        2.8922846e-08, 2.4457380e-08],
       [6.2616975e-03, 3.7964907e-01, 1.5404885e-02, ..., 2.1802803e-04,
        3.9599890e-05, 7.6596516e-05]], dtype=float32)

In [26]:
# Save the model
model.save("bachelor_trained_test.h5")

In [27]:
# Load the model
from keras.models import load_model
model = load_model("bachelor_trained_test.h5")

In [ ]:
# test predict with mock data 

# new_data = np.array([[0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]])

# prediction_class = model.predict_classes(new_data)

# print(f"Predicted class: {}")